"""create todos table

Revision ID: 3d922f7095ec
Revises: 
Create Date: 2025-07-30 13:28:07.407588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d922f7095ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contract_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_contact_number'), 'clients', ['contact_number'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('uniform_cost', sa.Float(), nullable=True),
    sa.Column('uniform_deducted_amount', sa.Float(), nullable=True),
    sa.Column('monthly_deduction', sa.Float(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', name='guardstatus'), nullable=True),
    sa.Column('current_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guards_contact_number'), 'guards', ['contact_number'], unique=True)
    op.create_index(op.f('ix_guards_id'), 'guards', ['id'], unique=False)
    op.create_table('duty_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_contact_number', sa.String(), nullable=False),
    sa.Column('client_contact_number', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duty_status', sa.Enum('ON_DUTY', 'OFF_DUTY', 'AVAILABLE', name='dutystatus'), nullable=True),
    sa.Column('shift_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_number'], ['clients.contact_number'], ),
    sa.ForeignKeyConstraint(['guard_contact_number'], ['guards.contact_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_assignments_id'), 'duty_assignments', ['id'], unique=False)
    op.create_table('inventory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_contact_number', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'RETURNED', 'LOST', name='inventorystatus'), nullable=True),
    sa.Column('condition_on_issue', sa.String(), nullable=True),
    sa.Column('condition_on_return', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guard_contact_number'], ['guards.contact_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_records_id'), 'inventory_records', ['id'], unique=False)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_contact_number', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('uniform_deduction', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('final_salary', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guard_contact_number'], ['guards.contact_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_id'), 'salary_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_records_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_inventory_records_id'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_duty_assignments_id'), table_name='duty_assignments')
    op.drop_table('duty_assignments')
    op.drop_index(op.f('ix_guards_id'), table_name='guards')
    op.drop_index(op.f('ix_guards_contact_number'), table_name='guards')
    op.drop_table('guards')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_contact_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
