"""add image column

Revision ID: 43e7610802c1
Revises: d6de80e7e5a7
Create Date: 2025-08-13 12:07:03.864327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e7610802c1'
down_revision: Union[str, Sequence[str], None] = 'd6de80e7e5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guards', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guards', 'image_url')
    # ### end Alembic commands ###
