"""add name section in assignment

Revision ID: aaa16520ef5a
Revises: fdb32a6173cf
Create Date: 2025-07-31 17:35:41.733362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa16520ef5a'
down_revision: Union[str, Sequence[str], None] = 'fdb32a6173cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_assignments', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_assignments', 'name')
    # ### end Alembic commands ###
