"""add column in guard

Revision ID: b061afd62e48
Revises: 43e7610802c1
Create Date: 2025-08-13 13:52:09.521301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b061afd62e48'
down_revision: Union[str, Sequence[str], None] = '43e7610802c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guards', sa.Column('cnic', sa.Integer(), nullable=True))
    op.add_column('guards', sa.Column('cnic_front_url', sa.String(), nullable=True))
    op.add_column('guards', sa.Column('cnic_back_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guards', 'cnic_back_url')
    op.drop_column('guards', 'cnic_front_url')
    op.drop_column('guards', 'cnic')
    # ### end Alembic commands ###
